"use client";
import Link from "next/link";
import { useState } from "react";
import { FiBookOpen, FiCheckCircle, FiMail, FiSend } from "react-icons/fi";

export default function SupportPage() {
  const [subject, setSubject] = useState(''); const [message, setMessage] = useState(''); const [priority, setPriority] = useState('NORMAL'); const [status, setStatus] = useState('');
  async function submit() { if (!subject.trim() || !message.trim()) { setStatus('Subject and message are required.'); return; } const r = await fetch('/api/fleet-records/support-ticket', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ name: subject, payload: { message, priority, status: 'OPEN' }, active: true }) }); if (r.ok) { setSubject(''); setMessage(''); setStatus('Your support ticket has been submitted.'); } else setStatus('The ticket could not be submitted.'); }
  return <div className="space-y-5 p-4 sm:p-6"><header><p className="text-xs font-semibold text-[#1a7a75]">Help centre</p><h1 className="text-xl font-extrabold text-[#0d4a47]">Support</h1><p className="mt-1 text-xs text-slate-500">Send a request to the Smart Tracker operations team.</p></header><div className="grid gap-4 lg:grid-cols-[1fr_280px]"><section className="space-y-4 rounded-md border border-slate-200 bg-white p-5"><label className="grid gap-1 text-xs font-bold text-slate-600">Subject<input value={subject} onChange={(e) => setSubject(e.target.value)} className="h-10 rounded-md border px-3 text-sm font-normal" /></label><label className="grid gap-1 text-xs font-bold text-slate-600">Priority<select value={priority} onChange={(e) => setPriority(e.target.value)} className="h-10 rounded-md border px-3 text-sm font-normal"><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label className="grid gap-1 text-xs font-bold text-slate-600">How can we help?<textarea value={message} onChange={(e) => setMessage(e.target.value)} rows={7} className="rounded-md border px-3 py-2 text-sm font-normal" /></label><button onClick={() => void submit()} className="inline-flex h-10 items-center gap-2 rounded-md bg-[#0d756d] px-5 text-xs font-bold text-white"><FiSend />Submit ticket</button>{status && <p className="flex items-center gap-2 text-xs text-[#0d756d]"><FiCheckCircle />{status}</p>}</section><aside className="space-y-3"><Link href="/resources/faqs" className="flex items-center gap-3 rounded-md border bg-white p-4 text-sm font-bold text-[#0d4a47]"><FiBookOpen />Frequently asked questions</Link><a href="mailto:support@smarttracker.cloud" className="flex items-center gap-3 rounded-md border bg-white p-4 text-sm font-bold text-[#0d4a47]"><FiMail />support@smarttracker.cloud</a></aside></div></div>;
}
