"use client";

import { useEffect, useMemo, useState } from "react";
import {
  FiAlertCircle,
  FiCalendar,
  FiChevronLeft,
  FiChevronRight,
  FiDownload,
  FiFilter,
  FiMail,
  FiMapPin,
  FiMoreVertical,
  FiRefreshCw,
  FiSearch,
  FiTruck,
  FiX,
} from "react-icons/fi";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AlertRow = Record<string, any>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DeviceRow = Record<string, any>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type SavedSettingRow = Record<string, any>;

type PeriodKey = "24h" | "7d" | "30d" | "all";

type AlertCategory = {
  key: string;
  title: string;
  description?: string;
  alertTypes: string[];
  autoGenerated: boolean;
  group?: string;
};

type AlertSettings = {
  subUserName: string;
  vehicleGroupName: string;
  vehicleIds: string[];
  webNotifications: boolean;
  sound: boolean;
  mobileNotifications: boolean;
  emailNotifications: boolean;
  tripsOnly: boolean;
};

const DEFAULT_ALERT_SETTINGS: AlertSettings = {
  subUserName: "all",
  vehicleGroupName: "all",
  vehicleIds: [],
  webNotifications: true,
  sound: false,
  mobileNotifications: true,
  emailNotifications: false,
  tripsOnly: false,
};

const ALERT_CATEGORIES: AlertCategory[] = [
  {
    key: "geofence",
    title: "Geofence Alerts (In/Out)",
    description: "Triggered when a device enters or leaves a pre-defined geographic perimeter (virtual zone).",
    alertTypes: ["GEOFENCE_ENTER", "GEOFENCE_EXIT"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "ignition",
    title: "Ignition On/Off (ACC Alert)",
    description: "Detects when the vehicle's engine key ignition status turns on or off.",
    alertTypes: ["IGNITION_ANOMALY", "IGNITION_ON", "IGNITION_OFF"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "unexpectedMovement",
    title: "Tow / Movement Alert",
    description: "Detects vehicle displacement or movement while the ignition remains off, such as being towed or rolled away.",
    alertTypes: ["UNEXPECTED_MOVEMENT", "IGNITION_ANOMALY"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "vibrationShock",
    title: "Vibration / Shock Alert",
    description: "Triggered by internal G-sensors when an impact, glass break, or physical tampering attempt is detected while parked.",
    alertTypes: ["VIBRATION_SHOCK", "SHOCK", "TAMPER"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "sos",
    title: "SOS / Panic Button Alert",
    description: "Immediate priority notification triggered when an onboard physical emergency button is pressed.",
    alertTypes: ["SOS", "PANIC"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "doorIntrusion",
    title: "Door Open / Intrusion Alert",
    description: "Fires when vehicle doors are opened unauthorizedly, usually tied to door sensor or CAN-bus inputs.",
    alertTypes: ["DOOR_OPEN", "INTRUSION"],
    autoGenerated: true,
    group: "Security & Theft Prevention Alerts",
  },
  {
    key: "overspeed",
    title: "Speeding Alert",
    description: "Triggers when a preset speed threshold or road-posted speed limit is exceeded.",
    alertTypes: ["OVERSPEED"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "acceleration",
    title: "Harsh Acceleration",
    description: "Rapid spike in forward G-force.",
    alertTypes: ["HARSH_ACCEL", "SUDDEN_ACCELERATION"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "braking",
    title: "Harsh Braking",
    description: "Sudden deceleration.",
    alertTypes: ["HARSH_BRAKE", "SUDDEN_BRAKING"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "cornering",
    title: "Harsh Cornering",
    description: "Lateral G-force spikes during sharp turns.",
    alertTypes: ["HARSH_CORNERING", "SHARP_TURN"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "idling",
    title: "Idling Alert",
    description: "Triggers when the ignition remains on without movement beyond a specified time threshold.",
    alertTypes: ["IDLE_EXCEEDED", "VEHICLE_IDLING"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "crash",
    title: "Crash / Impact Alert",
    description: "Triggers upon high G-force deceleration indicating a collision.",
    alertTypes: ["CRASH", "COLLISION", "IMPACT"],
    autoGenerated: true,
    group: "Driver Behavior & Telematics Alerts",
  },
  {
    key: "powerCut",
    title: "Main Power Cut Alert",
    description: "Fires immediately if the tracking unit is disconnected from the main external battery supply.",
    alertTypes: ["POWER_CUT"],
    autoGenerated: true,
    group: "Power & Hardware System Alerts",
  },
  {
    key: "vehicleBatteryLimit",
    title: "Low External Battery",
    description: "Warns when the main vehicle battery drops below safe voltage thresholds.",
    alertTypes: ["LOW_EXTERNAL_BATTERY", "VEHICLE_BATTERY_LIMIT", "DEVICE_BATTERY_LIMIT"],
    autoGenerated: true,
    group: "Power & Hardware System Alerts",
  },
  {
    key: "deviceLowBattery",
    title: "Low Internal Battery",
    description: "Indicates the device's internal backup battery power is running critically low after main power disconnection.",
    alertTypes: ["LOW_INTERNAL_BATTERY", "LOW_BATTERY", "DEVICE_LOW_BATTERY"],
    autoGenerated: true,
    group: "Power & Hardware System Alerts",
  },
  {
    key: "gpsSignalLoss",
    title: "GPS Signal Loss / Blind Spot Alert",
    description: "Warns when satellite fix is lost, such as underground parking or possible jammer activation.",
    alertTypes: ["GPS_SIGNAL_LOSS"],
    autoGenerated: true,
    group: "Power & Hardware System Alerts",
  },
  {
    key: "antennaTamper",
    title: "Antenna Cut / Tamper Alert",
    description: "Triggered if external GPS/GSM antennas are unplugged or damaged.",
    alertTypes: ["ANTENNA_CUT"],
    autoGenerated: true,
    group: "Power & Hardware System Alerts",
  },
  {
    key: "serviceDue",
    title: "Odometer / Service Alert",
    description: "Scheduled notifications based on total mileage, engine operating hours, or fixed calendar dates.",
    alertTypes: ["SERVICE_DUE"],
    autoGenerated: true,
    group: "Maintenance & Sensor-Based Alerts",
  },
  {
    key: "temperature",
    title: "Temperature Alerts",
    description: "Monitors cold chain cargo; triggers when ambient temperature strays out of upper/lower thresholds.",
    alertTypes: ["TEMPERATURE_ALERT"],
    autoGenerated: true,
    group: "Maintenance & Sensor-Based Alerts",
  },
  {
    key: "fuelTheft",
    title: "Fuel Level Alerts",
    description: "Detects sudden fuel drops, fuel theft signals, or unexpected rapid fuel consumption.",
    alertTypes: ["LOW_FUEL", "FUEL_DRAINAGE", "FUEL_THEFT"],
    autoGenerated: true,
    group: "Maintenance & Sensor-Based Alerts",
  },
  {
    key: "weightLoad",
    title: "Weight / Load Sensor Alert",
    description: "Triggers on unauthorized weight changes or cargo door openings on commercial trailers.",
    alertTypes: ["WEIGHT_LOAD_CHANGE"],
    autoGenerated: true,
    group: "Maintenance & Sensor-Based Alerts",
  },
  { key: "deviceRemoval", title: "Device Removal (External Power Disconnected)", alertTypes: ["EXTERNAL_POWER_DISCONNECTED", "DEVICE_REMOVAL"], autoGenerated: true },
  { key: "deviceDisassemble", title: "Device Disassemble", alertTypes: ["DEVICE_DISASSEMBLE", "TAMPER"], autoGenerated: false },
  { key: "powerOff", title: "Power Off", alertTypes: ["POWER_OFF"], autoGenerated: true },
  { key: "powerOn", title: "Power On", alertTypes: ["POWER_ON"], autoGenerated: true },
  { key: "refuelling", title: "Refuelling", alertTypes: ["REFUELLING"], autoGenerated: false },
  { key: "rfidTap", title: "Rfid Tap", alertTypes: ["RFID_TAP"], autoGenerated: false },
  { key: "routeDeviation", title: "Route Deviation", alertTypes: ["ROUTE_DEVIATION"], autoGenerated: false },
  { key: "shutdown", title: "Shutdown", alertTypes: ["SHUTDOWN"], autoGenerated: false },
  { key: "stoppage", title: "Stoppage", alertTypes: ["STOPPAGE"], autoGenerated: false },
  { key: "stoppageGeofence", title: "Stoppage in Geofence", alertTypes: ["STOPPAGE_IN_GEOFENCE"], autoGenerated: false },
  { key: "trip", title: "Trip", alertTypes: ["TRIP"], autoGenerated: false },
  { key: "tripDelay", title: "Trip Delay", alertTypes: ["TRIP_DELAY"], autoGenerated: false },
  { key: "tripUpdates", title: "Trip Updates", alertTypes: ["TRIP_UPDATE"], autoGenerated: false },
  { key: "arrival", title: "Vehicle Arrival", alertTypes: ["VEHICLE_ARRIVAL"], autoGenerated: false },
  { key: "dtc", title: "Vehicle DTC Fault", alertTypes: ["DTC_FAULT", "VEHICLE_DTC_FAULT"], autoGenerated: false },
];

const PERIODS: Record<PeriodKey, { label: string; ms: number | null }> = {
  "24h": { label: "Last 24 Hours", ms: 24 * 60 * 60 * 1000 },
  "7d": { label: "Last 7 Days", ms: 7 * 24 * 60 * 60 * 1000 },
  "30d": { label: "Last 30 Days", ms: 30 * 24 * 60 * 60 * 1000 },
  all: { label: "All Time", ms: null },
};

function norm(value?: string | null) {
  return String(value ?? "").trim().toUpperCase();
}

function alertTime(alert: AlertRow) {
  return alert.alertTime ?? alert.eventTime ?? alert.receivedAt ?? alert.createdAt ?? null;
}

function inPeriod(alert: AlertRow, period: PeriodKey) {
  const ms = PERIODS[period].ms;
  if (!ms) return true;
  const value = alertTime(alert);
  if (!value) return false;
  const time = new Date(value).getTime();
  return Number.isFinite(time) && Date.now() - time <= ms;
}

function dateText(value?: string | null) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString(undefined, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function shortName(value?: string | null) {
  const text = String(value ?? "Vehicle");
  return text.length > 22 ? `${text.slice(0, 18)}...${text.slice(-4)}` : text;
}

function categoryMatches(category: AlertCategory, alert: AlertRow) {
  const type = norm(alert.alertType ?? alert.type);
  return category.alertTypes.includes(type);
}

function categoryForAlert(alert: AlertRow) {
  return ALERT_CATEGORIES.find((category) => categoryMatches(category, alert));
}

function deviceLookup(devices: DeviceRow[]) {
  const byId = new Map<string, DeviceRow>();
  const byImei = new Map<string, DeviceRow>();
  devices.forEach((device) => {
    if (device.id) byId.set(String(device.id), device);
    if (device.imei) byImei.set(String(device.imei), device);
  });
  return { byId, byImei };
}

function vehicleName(alert: AlertRow, devices: ReturnType<typeof deviceLookup>) {
  const device = devices.byId.get(String(alert.deviceId ?? "")) ?? devices.byImei.get(String(alert.deviceImei ?? ""));
  return shortName(alert.vehiclePlate ?? alert.vehicleNumber ?? device?.vehiclePlate ?? device?.name ?? device?.imei ?? alert.deviceImei ?? alert.deviceId);
}

function driverName(alert: AlertRow, devices: ReturnType<typeof deviceLookup>) {
  const device = devices.byId.get(String(alert.deviceId ?? "")) ?? devices.byImei.get(String(alert.deviceImei ?? ""));
  return alert.driverName ?? device?.driverName ?? device?.ownerName ?? "Admin";
}

function deviceOptionLabel(device: DeviceRow) {
  return String(device.vehiclePlate ?? device.name ?? device.imei ?? device.id ?? "Vehicle");
}

function Toggle({
  checked,
  onChange,
  label,
}: {
  checked: boolean;
  onChange: (checked: boolean) => void;
  label: string;
}) {
  return (
    <button
      type="button"
      role="switch"
      aria-checked={checked}
      onClick={() => onChange(!checked)}
      className="flex w-full items-center justify-between gap-4 rounded-lg border border-[#edf2f6] bg-white px-4 py-3 text-left text-sm font-semibold text-[#536987]"
    >
      <span>{label}</span>
      <span
        className="relative h-6 w-11 rounded-full transition"
        style={{ background: checked ? "#23b8c8" : "#d5e2ec" }}
      >
        <span
          className="absolute top-1 h-4 w-4 rounded-full bg-white shadow transition"
          style={{ left: checked ? "23px" : "4px" }}
        />
      </span>
    </button>
  );
}

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertRow[]>([]);
  const [devices, setDevices] = useState<DeviceRow[]>([]);
  const [savedSettings, setSavedSettings] = useState<SavedSettingRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState<PeriodKey>("24h");
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState<"All" | "Critical" | "Non Critical">("All");
  const [selectedKey, setSelectedKey] = useState(ALERT_CATEGORIES[0].key);
  const [settingCategory, setSettingCategory] = useState<AlertCategory | null>(null);
  const [alertSettings, setAlertSettings] = useState<AlertSettings>(DEFAULT_ALERT_SETTINGS);
  const [settingsSaving, setSettingsSaving] = useState(false);
  const [settingsError, setSettingsError] = useState<string | null>(null);
  const [mountedAt, setMountedAt] = useState<string | null>(null);
  const [tableSearch, setTableSearch] = useState("");
  const [page, setPage] = useState(1);
  const pageSize = 10;

  async function load() {
    setLoading(true);
    try {
      const [alertRes, deviceRes, settingsRes] = await Promise.all([
        fetch("/api/telemetry?type=alerts&unacknowledgedOnly=false"),
        fetch("/api/devices"),
        fetch("/api/telemetry/alert-settings"),
      ]);

      if (alertRes.ok) {
        const data = await alertRes.json();
        const list: AlertRow[] = Array.isArray(data) ? data : data?.content ?? [];
        setAlerts(list.sort((a, b) => new Date(alertTime(b) ?? 0).getTime() - new Date(alertTime(a) ?? 0).getTime()));
      }
      if (deviceRes.ok) {
        const data = await deviceRes.json();
        setDevices(Array.isArray(data) ? data : data?.content ?? []);
      }
      if (settingsRes.ok) {
        const data = await settingsRes.json();
        setSavedSettings(Array.isArray(data) ? data : data?.content ?? []);
      }
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    setMountedAt(new Date().toISOString());
    load();
  }, []);

  const deviceMaps = useMemo(() => deviceLookup(devices), [devices]);
  const periodAlerts = useMemo(() => alerts.filter((alert) => inPeriod(alert, period)), [alerts, period]);
  const knownAlerts = useMemo(() => periodAlerts.filter((alert) => categoryForAlert(alert)), [periodAlerts]);
  const criticalCount = useMemo(() => knownAlerts.filter((alert) => norm(alert.severity) === "CRITICAL").length, [knownAlerts]);
  const configuredAlertCount = savedSettings.length;
  const nonCriticalCount = Math.max(knownAlerts.length - criticalCount, 0) + configuredAlertCount;

  const alertsByCategory = useMemo(() => {
    const grouped = new Map<string, AlertRow[]>();
    ALERT_CATEGORIES.forEach((category) => grouped.set(category.key, []));
    periodAlerts.forEach((alert) => {
      const category = categoryForAlert(alert);
      if (category) grouped.get(category.key)?.push(alert);
    });
    return grouped;
  }, [periodAlerts]);

  const categoryCounts = useMemo(() => {
    const counts = new Map<string, number>();
    ALERT_CATEGORIES.forEach((category) => counts.set(category.key, alertsByCategory.get(category.key)?.length ?? 0));
    return counts;
  }, [alertsByCategory]);

  const selectedCategory = ALERT_CATEGORIES.find((category) => category.key === selectedKey) ?? ALERT_CATEGORIES[0];
  const selectedAlerts = useMemo(() => alertsByCategory.get(selectedCategory.key) ?? [], [alertsByCategory, selectedCategory]);
  const filteredSelectedAlerts = useMemo(() => {
    const query = tableSearch.trim().toLowerCase();
    if (!query) return selectedAlerts;
    return selectedAlerts.filter((alert) => `${vehicleName(alert, deviceMaps)} ${driverName(alert, deviceMaps)} ${alert.message ?? ""} ${alert.relatedGeofenceName ?? ""} ${alert.alertType ?? ""}`.toLowerCase().includes(query));
  }, [selectedAlerts, tableSearch, deviceMaps]);
  const pageCount = Math.max(1, Math.ceil(filteredSelectedAlerts.length / pageSize));
  const pagedAlerts = filteredSelectedAlerts.slice((Math.min(page, pageCount) - 1) * pageSize, Math.min(page, pageCount) * pageSize);
  const savedSettingsByKey = useMemo(() => {
    const next = new Map<string, SavedSettingRow>();
    savedSettings.forEach((setting) => {
      if (setting.alertKey) next.set(String(setting.alertKey), setting);
    });
    return next;
  }, [savedSettings]);
  const uniqueDevices = useMemo(() => {
    const seen = new Set<string>();
    return devices.filter((device) => {
      const id = String(device.id ?? device.imei ?? "");
      if (!id || seen.has(id)) return false;
      seen.add(id);
      return true;
    });
  }, [devices]);

  const visibleCategories = ALERT_CATEGORIES.filter((category) => {
    const count = categoryCounts.get(category.key) ?? 0;
    const categoryAlerts = alertsByCategory.get(category.key) ?? [];
    const matchesSearch = `${category.title} ${category.description ?? ""}`.toLowerCase().includes(search.toLowerCase());
    const matchesSeverity =
      severityFilter === "All" ||
      (severityFilter === "Critical" && categoryAlerts.some((alert) => norm(alert.severity) === "CRITICAL")) ||
      (severityFilter === "Non Critical" && (count === 0 || categoryAlerts.some((alert) => norm(alert.severity) !== "CRITICAL")));
    return matchesSearch && matchesSeverity;
  });

  const showingFrom = (() => {
    if (!mountedAt) return PERIODS[period].label;
    const now = new Date(mountedAt);
    const ms = PERIODS[period].ms;
    if (!ms) return "All available alert history";
    return `${dateText(new Date(now.getTime() - ms).toISOString())} to ${dateText(now.toISOString())}`;
  })();

  function selectCategory(key: string) {
    setSelectedKey(key);
    setPage(1);
  }

  function exportAlerts() {
    const rows = filteredSelectedAlerts.map((alert) => [
      vehicleName(alert, deviceMaps),
      driverName(alert, deviceMaps),
      dateText(alertTime(alert)),
      alert.message ?? alert.relatedGeofenceName ?? alert.alertType ?? "",
      norm(alert.severity || "INFO"),
    ]);
    const csv = [["Vehicle Number", "Driver", "Alert Time", "Details", "Severity"], ...rows]
      .map((row) => row.map((cell) => `"${String(cell).replaceAll('"', '""')}"`).join(","))
      .join("\n");
    const link = document.createElement("a");
    link.href = URL.createObjectURL(new Blob([csv], { type: "text/csv" }));
    link.download = `${selectedCategory.key}-alerts.csv`;
    link.click();
    URL.revokeObjectURL(link.href);
  }

  async function openSettings(category: AlertCategory) {
    setSettingCategory(category);
    setAlertSettings(DEFAULT_ALERT_SETTINGS);
    setSettingsError(null);
    try {
      const res = await fetch(`/api/telemetry/alert-settings/${encodeURIComponent(category.key)}`, { cache: "no-store" });
      if (res.ok) {
        const saved = await res.json();
        setAlertSettings({
          subUserName: saved.subUserName ?? "all",
          vehicleGroupName: saved.vehicleGroupName ?? "all",
          vehicleIds: Array.isArray(saved.vehicleIds) ? saved.vehicleIds.map(String) : [],
          webNotifications: Boolean(saved.webNotifications),
          sound: Boolean(saved.sound),
          mobileNotifications: Boolean(saved.mobileAppNotifications),
          emailNotifications: Boolean(saved.emailNotifications),
          tripsOnly: Boolean(saved.tripsOnly),
        });
      }
    } catch {
      setSettingsError("Could not load saved alert settings.");
    }
  }

  function updateSettings<K extends keyof AlertSettings>(key: K, value: AlertSettings[K]) {
    setAlertSettings((prev) => ({ ...prev, [key]: value }));
  }

  function toggleVehicle(device: DeviceRow) {
    const id = String(device.id ?? device.imei ?? "");
    if (!id) return;
    setAlertSettings((prev) => ({
      ...prev,
      vehicleIds: prev.vehicleIds.includes(id)
        ? prev.vehicleIds.filter((vehicleId) => vehicleId !== id)
        : [...prev.vehicleIds, id],
    }));
  }

  async function saveSettings() {
    if (!settingCategory) return;
    setSettingsSaving(true);
    setSettingsError(null);
    try {
      const res = await fetch(`/api/telemetry/alert-settings/${encodeURIComponent(settingCategory.key)}`, {
        method: "PUT",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({
          alertTitle: settingCategory.title,
          subUserName: alertSettings.subUserName,
          vehicleGroupName: alertSettings.vehicleGroupName,
          vehicleIds: alertSettings.vehicleIds,
          webNotifications: alertSettings.webNotifications,
          sound: alertSettings.sound,
          mobileAppNotifications: alertSettings.mobileNotifications,
          emailNotifications: alertSettings.emailNotifications,
          tripsOnly: alertSettings.tripsOnly,
        }),
      });
      if (!res.ok) {
        const data = await res.json().catch(() => null);
        throw new Error(data?.message ?? "Could not save alert settings.");
      }
      const saved = await res.json().catch(() => null);
      if (saved?.alertKey) {
        setSavedSettings((prev) => [
          ...prev.filter((setting) => String(setting.alertKey) !== String(saved.alertKey)),
          saved,
        ]);
        setSelectedKey(String(saved.alertKey));
        setSeverityFilter("All");
        setSearch("");
        void load();
      }
      setSettingCategory(null);
    } catch (error) {
      setSettingsError(error instanceof Error ? error.message : "Could not save alert settings.");
    } finally {
      setSettingsSaving(false);
    }
  }

  return (
    <div className="flex h-[calc(100vh-88px)] min-h-[680px] overflow-hidden bg-[#f7faf9] text-[#102a2d] max-lg:h-auto max-lg:min-h-0 max-lg:flex-col max-lg:overflow-visible">
      <aside className="flex w-[300px] shrink-0 flex-col border-r border-[#e2ecea] bg-white max-lg:w-full max-lg:border-b max-lg:border-r-0">
        <div className="flex gap-2 border-b border-[#edf3f2] p-4">
          <div className="relative min-w-0 flex-1">
            <FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-[#7b9191]" size={16} />
            <input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search alerts..." className="h-10 w-full rounded-md border border-[#dce7e5] bg-white pl-9 pr-3 text-xs font-medium outline-none focus:border-[#0b756c]" />
          </div>
          <button type="button" className="grid h-10 w-10 shrink-0 place-items-center rounded-md border border-[#dce7e5] bg-white text-[#52706e]" aria-label="Filter alert types"><FiFilter size={17} /></button>
        </div>

        <div className="space-y-2 border-b border-[#edf3f2] p-4">
          {[
            { key: "All", label: "All Alerts", count: knownAlerts.length + configuredAlertCount, color: "#08766c", bg: "#08766c" },
            { key: "Critical", label: "Critical", count: criticalCount, color: "#ef476f", bg: "#fff5f6" },
            { key: "Non Critical", label: "Non Critical", count: nonCriticalCount, color: "#e49a13", bg: "#fffaf0" },
          ].map((item) => (
            <button key={item.key} type="button" onClick={() => setSeverityFilter(item.key as typeof severityFilter)} className="flex h-10 w-full items-center justify-between rounded-md px-3 text-xs font-bold transition" style={{ background: severityFilter === item.key ? item.bg : "transparent", color: severityFilter === item.key && item.key === "All" ? "white" : item.color }}>
              <span className="flex items-center gap-2">{item.key !== "All" && <FiAlertCircle size={15} />}{item.label}</span>
              <strong className="text-base">{loading ? "..." : item.count}</strong>
            </button>
          ))}
        </div>

        <div className="border-b border-[#edf3f2] px-4 py-4">
          <p className="mb-2 text-[10px] font-extrabold uppercase text-[#496765]">Showing alerts from</p>
          <div className="flex items-center gap-2 rounded-md border border-[#dce7e5] px-3 py-2 text-xs font-semibold text-[#52706e]"><FiCalendar size={14} /><span className="truncate">{showingFrom}</span></div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto p-3 max-lg:max-h-[420px]">
          {loading ? <div className="p-5 text-sm font-semibold text-[#78908e]">Loading alerts...</div> : visibleCategories.length === 0 ? <div className="p-5 text-sm font-semibold text-[#78908e]">No alert category matches your search.</div> : visibleCategories.map((category, index) => {
            const count = categoryCounts.get(category.key) ?? 0;
            const isConfigured = savedSettingsByKey.has(category.key);
            const selected = selectedCategory.key === category.key;
            const showGroup = category.group && category.group !== visibleCategories[index - 1]?.group;
            return <div key={category.key}>
              {showGroup && <div className="mb-2 mt-3 px-1 text-[10px] font-extrabold uppercase text-[#0b756c]">{category.group}</div>}
              <button type="button" onClick={() => selectCategory(category.key)} className="mb-2 w-full rounded-md border p-3 text-left transition" style={{ borderColor: selected ? "#b9ddd8" : "#e8efee", background: selected ? "#f2fbf9" : "#fff" }}>
                <div className="flex gap-3">
                  <span className="grid h-10 w-10 shrink-0 place-items-center rounded-full border border-[#b9ddd8] bg-[#f2fbf9] text-[#08766c]">{category.key === "geofence" ? <FiMapPin size={18} /> : category.key === "unexpectedMovement" ? <FiTruck size={18} /> : <FiAlertCircle size={18} />}</span>
                  <span className="min-w-0 flex-1">
                    <span className="block text-xs font-extrabold leading-5 text-[#294946]">{category.title} <b className="text-[#08766c]">{count > 0 ? `: ${count}` : isConfigured ? ": Alert Set" : ""}</b></span>
                    {category.description && <span className="mt-1 block text-[10px] font-medium leading-4 text-[#718986]">{category.description}</span>}
                    <span className="mt-2 inline-flex rounded-full bg-[#ddf4ef] px-2.5 py-1 text-[9px] font-bold text-[#08766c]">{isConfigured ? "Configured" : category.autoGenerated ? "Auto Generated" : "Not Configured"}</span>
                    <span onClick={(event) => { event.stopPropagation(); void openSettings(category); }} className="mt-2 block cursor-pointer text-[10px] font-bold text-[#0b8b80]">Set alert to receive notifications</span>
                  </span>
                </div>
              </button>
            </div>;
          })}
        </div>
      </aside>

      <main className="min-w-0 flex-1 overflow-hidden p-5 max-lg:min-h-[720px] max-sm:p-3">
        <div className="mb-5 flex flex-wrap items-start justify-between gap-4">
          <div><h1 className="text-2xl font-extrabold text-[#173d3a]">Alerts</h1><p className="mt-1 text-xs font-medium text-[#6d8381]">Monitor and manage all vehicle alerts in real time.</p></div>
          <div className="flex flex-wrap items-center gap-2">
            <label className="flex h-10 items-center gap-2 rounded-md border border-[#dce7e5] bg-white px-3 text-xs font-semibold text-[#45635f]"><FiCalendar size={15} /><select value={period} onChange={(event) => { setPeriod(event.target.value as PeriodKey); setPage(1); }} className="bg-transparent outline-none">{Object.entries(PERIODS).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}</select></label>
            <button type="button" onClick={() => setSeverityFilter(severityFilter === "All" ? "Critical" : severityFilter === "Critical" ? "Non Critical" : "All")} className="inline-flex h-10 items-center gap-2 rounded-md border border-[#dce7e5] bg-white px-3 text-xs font-bold text-[#45635f]"><FiFilter size={15} />Filters</button>
            <button type="button" onClick={() => setTableSearch(tableSearch ? "" : search)} className="grid h-10 w-10 place-items-center rounded-md border border-[#dce7e5] bg-white text-[#45635f]" aria-label="Search table"><FiSearch size={17} /></button>
            <button type="button" onClick={exportAlerts} className="grid h-10 w-10 place-items-center rounded-md border border-[#dce7e5] bg-white text-[#45635f]" aria-label="Download alerts"><FiDownload size={17} /></button>
            <button type="button" className="grid h-10 w-10 place-items-center rounded-md border border-[#dce7e5] bg-white text-[#45635f]" aria-label="Send alerts"><FiMail size={17} /></button>
            <button type="button" onClick={load} className="grid h-10 w-10 place-items-center rounded-md border border-[#dce7e5] bg-white text-[#45635f]" aria-label="Refresh alerts"><FiRefreshCw size={17} /></button>
          </div>
        </div>

        {tableSearch !== "" && <div className="relative mb-3 max-w-sm"><FiSearch className="absolute left-3 top-1/2 -translate-y-1/2 text-[#78908e]" size={15} /><input autoFocus value={tableSearch} onChange={(event) => { setTableSearch(event.target.value); setPage(1); }} placeholder="Search table..." className="h-10 w-full rounded-md border border-[#dce7e5] bg-white pl-9 pr-9 text-xs outline-none" /><button type="button" onClick={() => setTableSearch("")} className="absolute right-3 top-1/2 -translate-y-1/2 text-[#78908e]" aria-label="Close search"><FiX /></button></div>}

        <div className="mb-3 flex items-center gap-2"><h2 className="text-sm font-extrabold text-[#173d3a]">{selectedCategory.title} Alerts</h2><span className="rounded-full bg-[#ddf4ef] px-2.5 py-1 text-[10px] font-bold text-[#08766c]">{filteredSelectedAlerts.length}</span></div>

        <div className="overflow-hidden rounded-md border border-[#e3ecea] bg-white">
          <div className="grid grid-cols-[1.15fr_.8fr_.9fr_1.45fr_.65fr_28px] gap-3 bg-[#f0f7f6] px-4 py-3 text-[10px] font-extrabold text-[#55716e] max-md:hidden"><div>Vehicle Number</div><div>Driver</div><div>Alert Time</div><div>Details</div><div>Severity</div><div /></div>
          <div className="max-h-[calc(100vh-300px)] min-h-[360px] overflow-auto">
            {loading ? <div className="py-16 text-center text-sm font-semibold text-[#78908e]">Loading alerts...</div> : pagedAlerts.length === 0 ? <div className="py-16 text-center text-sm font-semibold text-[#78908e]">No records for this alert type in the selected period.</div> : pagedAlerts.map((alert) => {
              const severity = norm(alert.severity || "INFO");
              const critical = severity === "CRITICAL";
              return <div key={alert.id ?? `${alert.alertType}-${alertTime(alert)}`} className="grid min-h-[68px] grid-cols-[1.15fr_.8fr_.9fr_1.45fr_.65fr_28px] items-center gap-3 border-b border-[#edf3f2] px-4 py-3 text-xs text-[#496562] last:border-b-0 max-md:grid-cols-[1fr_auto] max-md:gap-y-2">
                <div className="flex min-w-0 items-center gap-3"><span className="grid h-8 w-8 shrink-0 place-items-center rounded-full bg-[#e4f6f2] text-[#08766c]"><FiTruck size={15} /></span><span className="min-w-0"><strong className="block truncate text-[#173d3a]">{vehicleName(alert, deviceMaps)}</strong><span className="mt-0.5 block truncate text-[10px]">{alert.vehiclePlate ?? alert.deviceImei ?? "Tracked vehicle"}</span></span></div>
                <div className="flex items-center gap-2 max-md:justify-end"><span className="grid h-7 w-7 place-items-center rounded-full bg-[#e4f6f2] text-[10px] font-extrabold text-[#08766c]">{driverName(alert, deviceMaps).charAt(0).toUpperCase()}</span><span className="truncate">{driverName(alert, deviceMaps)}</span></div>
                <div className="flex items-center gap-2"><FiCalendar className="shrink-0 text-[#08766c]" size={15} /><span>{dateText(alertTime(alert))}</span></div>
                <div className="min-w-0 max-md:text-right"><div className="flex items-center gap-2 max-md:justify-end"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#08766c]" /><span className="truncate">{alert.message ?? alert.relatedGeofenceName ?? alert.alertType ?? "-"}</span></div>{(alert.address || alert.relatedGeofenceName) && <div className="mt-1 flex items-center gap-1 truncate text-[10px] text-[#78908e] max-md:justify-end"><FiMapPin size={11} />{alert.address ?? alert.relatedGeofenceName}</div>}</div>
                <div><span className="inline-flex rounded-full px-2.5 py-1 text-[9px] font-bold" style={{ color: critical ? "#df365f" : "#c67e00", background: critical ? "#fff1f4" : "#fff7e7" }}>{critical ? "Critical" : "Non Critical"}</span></div>
                <button type="button" className="grid h-7 w-7 place-items-center text-[#59716f]" aria-label="Alert options"><FiMoreVertical size={16} /></button>
              </div>;
            })}
          </div>
        </div>

        <div className="mt-4 flex flex-wrap items-center justify-between gap-3 text-xs font-semibold text-[#5f7774]">
          <span>Showing {filteredSelectedAlerts.length === 0 ? 0 : (Math.min(page, pageCount) - 1) * pageSize + 1} to {Math.min(Math.min(page, pageCount) * pageSize, filteredSelectedAlerts.length)} of {filteredSelectedAlerts.length} alerts</span>
          <div className="flex items-center gap-1"><button type="button" disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className="grid h-8 w-8 place-items-center rounded-md border border-[#dce7e5] bg-white disabled:opacity-40" aria-label="Previous page"><FiChevronLeft /></button>{Array.from({ length: Math.min(pageCount, 5) }, (_, index) => index + 1).map((number) => <button key={number} type="button" onClick={() => setPage(number)} className="grid h-8 w-8 place-items-center rounded-md border text-xs font-bold" style={{ background: page === number ? "#08766c" : "white", borderColor: page === number ? "#08766c" : "#dce7e5", color: page === number ? "white" : "#496562" }}>{number}</button>)}<button type="button" disabled={page >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))} className="grid h-8 w-8 place-items-center rounded-md border border-[#dce7e5] bg-white disabled:opacity-40" aria-label="Next page"><FiChevronRight /></button></div>
        </div>
      </main>

      {settingCategory && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-[#061337]/45 px-4 py-6">
          <div className="max-h-[92vh] w-full max-w-[720px] overflow-hidden rounded-xl bg-white shadow-[0_24px_80px_rgba(6,19,55,0.25)]">
            <div className="flex items-center justify-between border-b border-[#edf2f6] px-6 py-5">
              <div>
                <h3 className="text-lg font-extrabold text-[#061337]">Alert Details</h3>
                <p className="mt-1 text-sm font-semibold text-[#536987]">{settingCategory.title}</p>
              </div>
              <button
                type="button"
                onClick={() => setSettingCategory(null)}
                className="grid h-9 w-9 place-items-center rounded-lg bg-[#f4f8fb] text-[#536987]"
                aria-label="Close alert settings"
              >
                <FiX size={20} />
              </button>
            </div>

            <div className="max-h-[calc(92vh-82px)] overflow-y-auto px-6 py-5">
              <div className="grid gap-4 md:grid-cols-2">
                <label className="grid gap-2 text-sm font-bold text-[#536987]">
                  <span>Sub User Name</span>
                  <select
                    value={alertSettings.subUserName}
                    onChange={(event) => updateSettings("subUserName", event.target.value)}
                    className="h-11 rounded-lg border border-[#d5e2ec] bg-white px-3 text-sm font-semibold text-[#061337] outline-none"
                  >
                    <option value="all">All Subusers</option>
                  </select>
                </label>

                <label className="grid gap-2 text-sm font-bold text-[#536987]">
                  <span>Vehicle Group Name</span>
                  <select
                    value={alertSettings.vehicleGroupName}
                    onChange={(event) => updateSettings("vehicleGroupName", event.target.value)}
                    className="h-11 rounded-lg border border-[#d5e2ec] bg-white px-3 text-sm font-semibold text-[#061337] outline-none"
                  >
                    <option value="all">All Vehicle Group Name</option>
                  </select>
                </label>
              </div>

              <div className="mt-5 grid gap-2 text-sm font-bold text-[#536987]">
                <span>Vehicles*</span>
                <div className="max-h-44 overflow-y-auto rounded-lg border border-[#d5e2ec] bg-white p-2">
                  {uniqueDevices.length === 0 ? (
                    <div className="px-3 py-4 text-sm font-semibold text-[#7890aa]">Select Vehicles</div>
                  ) : (
                    uniqueDevices.map((device) => {
                      const id = String(device.id ?? device.imei ?? "");
                      const checked = alertSettings.vehicleIds.includes(id);
                      return (
                        <button
                          key={id}
                          type="button"
                          onClick={() => toggleVehicle(device)}
                          className="flex w-full items-center justify-between rounded-md px-3 py-2 text-left text-sm font-semibold text-[#061337] hover:bg-[#f4f8fb]"
                        >
                          <span className="truncate">{deviceOptionLabel(device)}</span>
                          <span
                            className="grid h-5 w-5 place-items-center rounded border text-[11px]"
                            style={{
                              borderColor: checked ? "#23b8c8" : "#c9d8e5",
                              background: checked ? "#23b8c8" : "#fff",
                              color: "#fff",
                            }}
                          >
                            {checked ? "✓" : ""}
                          </span>
                        </button>
                      );
                    })
                  )}
                </div>
              </div>

              {settingsError && (
                <div className="mt-5 rounded-lg border border-[#fecaca] bg-[#fef2f2] px-4 py-3 text-sm font-semibold text-[#b91c1c]">
                  {settingsError}
                </div>
              )}

              <div className="mt-6">
                <h4 className="text-base font-extrabold text-[#061337]">Notifications</h4>
                <div className="mt-3 grid gap-3 md:grid-cols-2">
                  <Toggle
                    label="Web Notifications"
                    checked={alertSettings.webNotifications}
                    onChange={(checked) => updateSettings("webNotifications", checked)}
                  />
                  <Toggle
                    label="Enable sound"
                    checked={alertSettings.sound}
                    onChange={(checked) => updateSettings("sound", checked)}
                  />
                  <Toggle
                    label="Mobile App Notifications"
                    checked={alertSettings.mobileNotifications}
                    onChange={(checked) => updateSettings("mobileNotifications", checked)}
                  />
                  <Toggle
                    label="Email Notifications"
                    checked={alertSettings.emailNotifications}
                    onChange={(checked) => updateSettings("emailNotifications", checked)}
                  />
                </div>
              </div>

              <div className="mt-6">
                <h4 className="text-base font-extrabold text-[#061337]">Notification Settings</h4>
                <p className="mt-2 text-sm font-semibold leading-6 text-[#536987]">
                  Above enabled notifications will only be sent based on the following conditions.
                </p>
                <div className="mt-3 rounded-lg border border-[#edf2f6] bg-[#f8fafc] p-4">
                  <div className="mb-3 text-sm font-extrabold text-[#061337]">Trips</div>
                  <Toggle
                    label="Send notifications only when vehicle is on a trip."
                    checked={alertSettings.tripsOnly}
                    onChange={(checked) => updateSettings("tripsOnly", checked)}
                  />
                </div>
              </div>

              <div className="mt-6 flex items-center justify-end gap-3 border-t border-[#edf2f6] pt-5">
                <button
                  type="button"
                  onClick={() => setSettingCategory(null)}
                  className="h-10 rounded-lg border border-[#d5e2ec] px-5 text-sm font-bold text-[#536987]"
                >
                  Cancel
                </button>
                <button
                  type="button"
                  onClick={saveSettings}
                  disabled={settingsSaving}
                  className="h-10 rounded-lg bg-[#23b8c8] px-5 text-sm font-bold text-white disabled:opacity-60"
                >
                  {settingsSaving ? "Saving..." : "Save Alert"}
                </button>
              </div>
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
