"use client";

import { useEffect, useMemo, useState } from "react";
import {
  FiAlertCircle,
  FiBell,
  FiChevronLeft,
  FiChevronRight,
  FiDownload,
  FiMail,
  FiSearch,
} from "react-icons/fi";

// eslint-disable-next-line @typescript-eslint/no-explicit-any
type AlertRow = Record<string, any>;
// eslint-disable-next-line @typescript-eslint/no-explicit-any
type DeviceRow = Record<string, any>;

type PeriodKey = "24h" | "7d" | "30d" | "all";

type AlertCategory = {
  key: string;
  title: string;
  description?: string;
  alertTypes: string[];
  autoGenerated: boolean;
};

const ALERT_CATEGORIES: AlertCategory[] = [
  {
    key: "ignition",
    title: "Ignition on/off",
    description: "Ignition alert is triggered when the system detects your vehicle's ignition as turned on or off.",
    alertTypes: ["IGNITION_ANOMALY", "IGNITION_ON", "IGNITION_OFF"],
    autoGenerated: true,
  },
  { key: "crash", title: "Crash", alertTypes: ["CRASH", "COLLISION"], autoGenerated: true },
  { key: "deviceBatteryLimit", title: "Device Battery below set limit", alertTypes: ["DEVICE_BATTERY_LIMIT"], autoGenerated: false },
  { key: "deviceRemoval", title: "Device Removal (External Power Disconnected)", alertTypes: ["POWER_CUT", "EXTERNAL_POWER_DISCONNECTED", "DEVICE_REMOVAL"], autoGenerated: true },
  { key: "deviceDisassemble", title: "Device Disassemble", alertTypes: ["DEVICE_DISASSEMBLE", "TAMPER"], autoGenerated: false },
  { key: "geofence", title: "Geofence entry/exit", alertTypes: ["GEOFENCE_ENTER", "GEOFENCE_EXIT"], autoGenerated: true },
  { key: "deviceLowBattery", title: "Device Low Battery", alertTypes: ["LOW_BATTERY", "DEVICE_LOW_BATTERY"], autoGenerated: true },
  { key: "unexpectedMovement", title: "Unexpected Movement", alertTypes: ["UNEXPECTED_MOVEMENT"], autoGenerated: false },
  { key: "overspeed", title: "Overspeed", alertTypes: ["OVERSPEED"], autoGenerated: false },
  { key: "fuelTheft", title: "Possible Fuel Theft", alertTypes: ["FUEL_DRAINAGE", "FUEL_THEFT"], autoGenerated: false },
  { key: "powerCut", title: "Power Cut", alertTypes: ["POWER_CUT"], autoGenerated: true },
  { key: "powerOff", title: "Power Off", alertTypes: ["POWER_OFF"], autoGenerated: true },
  { key: "powerOn", title: "Power On", alertTypes: ["POWER_ON"], autoGenerated: true },
  { key: "refuelling", title: "Refuelling", alertTypes: ["REFUELLING"], autoGenerated: false },
  { key: "rfidTap", title: "Rfid Tap", alertTypes: ["RFID_TAP"], autoGenerated: false },
  { key: "routeDeviation", title: "Route Deviation", alertTypes: ["ROUTE_DEVIATION"], autoGenerated: false },
  { key: "sharpTurn", title: "Sharp Turn", alertTypes: ["SHARP_TURN"], autoGenerated: true },
  { key: "shutdown", title: "Shutdown", alertTypes: ["SHUTDOWN"], autoGenerated: false },
  { key: "sos", title: "SOS", alertTypes: ["SOS"], autoGenerated: true },
  { key: "stoppage", title: "Stoppage", alertTypes: ["STOPPAGE"], autoGenerated: false },
  { key: "stoppageGeofence", title: "Stoppage in Geofence", alertTypes: ["STOPPAGE_IN_GEOFENCE"], autoGenerated: false },
  { key: "acceleration", title: "Sudden Acceleration", alertTypes: ["HARSH_ACCEL", "SUDDEN_ACCELERATION"], autoGenerated: true },
  { key: "braking", title: "Sudden Braking", alertTypes: ["HARSH_BRAKE", "SUDDEN_BRAKING"], autoGenerated: true },
  { key: "trip", title: "Trip", alertTypes: ["TRIP"], autoGenerated: false },
  { key: "tripDelay", title: "Trip Delay", alertTypes: ["TRIP_DELAY"], autoGenerated: false },
  { key: "tripUpdates", title: "Trip Updates", alertTypes: ["TRIP_UPDATE"], autoGenerated: false },
  { key: "arrival", title: "Vehicle Arrival", alertTypes: ["VEHICLE_ARRIVAL"], autoGenerated: false },
  { key: "dtc", title: "Vehicle DTC Fault", alertTypes: ["DTC_FAULT", "VEHICLE_DTC_FAULT"], autoGenerated: false },
  { key: "idling", title: "Vehicle Idling", alertTypes: ["IDLE_EXCEEDED", "VEHICLE_IDLING"], autoGenerated: false },
  { key: "vehicleBatteryLimit", title: "Vehicle Battery below set limit", alertTypes: ["VEHICLE_BATTERY_LIMIT"], autoGenerated: false },
];

const PERIODS: Record<PeriodKey, { label: string; ms: number | null }> = {
  "24h": { label: "Last 24 Hours", ms: 24 * 60 * 60 * 1000 },
  "7d": { label: "Last 7 Days", ms: 7 * 24 * 60 * 60 * 1000 },
  "30d": { label: "Last 30 Days", ms: 30 * 24 * 60 * 60 * 1000 },
  all: { label: "All Time", ms: null },
};

const SEVERITY_STYLE: Record<string, string> = {
  CRITICAL: "#EF4444",
  WARNING: "#F59E0B",
  INFO: "#1A7A75",
};

function norm(value?: string | null) {
  return String(value ?? "").trim().toUpperCase();
}

function alertTime(alert: AlertRow) {
  return alert.alertTime ?? alert.eventTime ?? alert.receivedAt ?? alert.createdAt ?? null;
}

function inPeriod(alert: AlertRow, period: PeriodKey) {
  const ms = PERIODS[period].ms;
  if (!ms) return true;
  const value = alertTime(alert);
  if (!value) return false;
  const time = new Date(value).getTime();
  return Number.isFinite(time) && Date.now() - time <= ms;
}

function dateText(value?: string | null) {
  if (!value) return "-";
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "-";
  return date.toLocaleString(undefined, {
    day: "2-digit",
    month: "2-digit",
    year: "numeric",
    hour: "numeric",
    minute: "2-digit",
  });
}

function shortName(value?: string | null) {
  const text = String(value ?? "Vehicle");
  return text.length > 22 ? `${text.slice(0, 18)}...${text.slice(-4)}` : text;
}

function categoryMatches(category: AlertCategory, alert: AlertRow) {
  const type = norm(alert.alertType ?? alert.type);
  return category.alertTypes.includes(type);
}

function categoryForAlert(alert: AlertRow) {
  return ALERT_CATEGORIES.find((category) => categoryMatches(category, alert));
}

function deviceLookup(devices: DeviceRow[]) {
  const byId = new Map<string, DeviceRow>();
  const byImei = new Map<string, DeviceRow>();
  devices.forEach((device) => {
    if (device.id) byId.set(String(device.id), device);
    if (device.imei) byImei.set(String(device.imei), device);
  });
  return { byId, byImei };
}

function vehicleName(alert: AlertRow, devices: ReturnType<typeof deviceLookup>) {
  const device = devices.byId.get(String(alert.deviceId ?? "")) ?? devices.byImei.get(String(alert.deviceImei ?? ""));
  return shortName(alert.vehiclePlate ?? alert.vehicleNumber ?? device?.vehiclePlate ?? device?.name ?? device?.imei ?? alert.deviceImei ?? alert.deviceId);
}

function driverName(alert: AlertRow, devices: ReturnType<typeof deviceLookup>) {
  const device = devices.byId.get(String(alert.deviceId ?? "")) ?? devices.byImei.get(String(alert.deviceImei ?? ""));
  return alert.driverName ?? device?.driverName ?? device?.ownerName ?? "Admin";
}

export default function AlertsPage() {
  const [alerts, setAlerts] = useState<AlertRow[]>([]);
  const [devices, setDevices] = useState<DeviceRow[]>([]);
  const [loading, setLoading] = useState(true);
  const [period, setPeriod] = useState<PeriodKey>("24h");
  const [search, setSearch] = useState("");
  const [severityFilter, setSeverityFilter] = useState<"All" | "Critical" | "Non Critical">("All");
  const [selectedKey, setSelectedKey] = useState(ALERT_CATEGORIES[0].key);

  async function load() {
    setLoading(true);
    try {
      const [alertRes, deviceRes] = await Promise.all([
        fetch("/api/telemetry?type=alerts&unacknowledgedOnly=false"),
        fetch("/api/devices"),
      ]);

      if (alertRes.ok) {
        const data = await alertRes.json();
        const list: AlertRow[] = Array.isArray(data) ? data : data?.content ?? [];
        setAlerts(list.sort((a, b) => new Date(alertTime(b) ?? 0).getTime() - new Date(alertTime(a) ?? 0).getTime()));
      }
      if (deviceRes.ok) {
        const data = await deviceRes.json();
        setDevices(Array.isArray(data) ? data : data?.content ?? []);
      }
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { load(); }, []);

  const deviceMaps = useMemo(() => deviceLookup(devices), [devices]);
  const periodAlerts = useMemo(() => alerts.filter((alert) => inPeriod(alert, period)), [alerts, period]);
  const knownAlerts = useMemo(() => periodAlerts.filter((alert) => categoryForAlert(alert)), [periodAlerts]);
  const criticalCount = useMemo(() => knownAlerts.filter((alert) => norm(alert.severity) === "CRITICAL").length, [knownAlerts]);
  const nonCriticalCount = Math.max(knownAlerts.length - criticalCount, 0);

  const alertsByCategory = useMemo(() => {
    const grouped = new Map<string, AlertRow[]>();
    ALERT_CATEGORIES.forEach((category) => grouped.set(category.key, []));
    periodAlerts.forEach((alert) => {
      const category = categoryForAlert(alert);
      if (category) grouped.get(category.key)?.push(alert);
    });
    return grouped;
  }, [periodAlerts]);

  const categoryCounts = useMemo(() => {
    const counts = new Map<string, number>();
    ALERT_CATEGORIES.forEach((category) => counts.set(category.key, alertsByCategory.get(category.key)?.length ?? 0));
    return counts;
  }, [alertsByCategory]);

  const selectedCategory = ALERT_CATEGORIES.find((category) => category.key === selectedKey) ?? ALERT_CATEGORIES[0];
  const selectedAlerts = useMemo(() => alertsByCategory.get(selectedCategory.key) ?? [], [alertsByCategory, selectedCategory]);

  const visibleCategories = ALERT_CATEGORIES.filter((category) => {
    const count = categoryCounts.get(category.key) ?? 0;
    const categoryAlerts = alertsByCategory.get(category.key) ?? [];
    const matchesSearch = `${category.title} ${category.description ?? ""}`.toLowerCase().includes(search.toLowerCase());
    const matchesSeverity =
      severityFilter === "All" ||
      (severityFilter === "Critical" && categoryAlerts.some((alert) => norm(alert.severity) === "CRITICAL")) ||
      (severityFilter === "Non Critical" && (count === 0 || categoryAlerts.some((alert) => norm(alert.severity) !== "CRITICAL")));
    return matchesSearch && matchesSeverity;
  });

  const showingFrom = (() => {
    const now = new Date();
    const ms = PERIODS[period].ms;
    if (!ms) return "All available alert history";
    return `${dateText(new Date(now.getTime() - ms).toISOString())} to ${dateText(now.toISOString())}`;
  })();

  return (
    <div className="flex h-[calc(100vh-88px)] min-h-[680px] overflow-hidden bg-[#f3f7fa] text-[#061337]">
      <aside className="flex w-[350px] shrink-0 flex-col border-r border-[#d7e2ec] bg-white">
        <div className="border-b border-[#edf2f6] p-4">
          <div className="relative">
            <FiSearch className="absolute right-4 top-1/2 -translate-y-1/2 text-[#9bb0c6]" size={22} />
            <input
              value={search}
              onChange={(event) => setSearch(event.target.value)}
              placeholder="Type to search"
              className="h-12 w-full rounded-lg border border-[#d5e2ec] bg-white px-4 pr-12 text-sm font-medium text-[#061337] outline-none placeholder:text-[#b6c8d9]"
            />
          </div>
        </div>

        <div className="border-b border-[#edf2f6] px-4 py-3">
          <div className="flex flex-wrap gap-2">
            {[
              { key: "All", label: "All", count: knownAlerts.length },
              { key: "Critical", label: "Critical", count: criticalCount },
              { key: "Non Critical", label: "Non Critical", count: nonCriticalCount },
            ].map((item) => (
              <button
                key={item.key}
                type="button"
                onClick={() => setSeverityFilter(item.key as typeof severityFilter)}
                className="inline-flex h-9 items-center gap-2 rounded-full px-3 text-xs font-bold transition"
                style={{
                  border: `1px solid ${severityFilter === item.key ? "#23b8c8" : "#edf2f6"}`,
                  background: severityFilter === item.key ? "#eefcff" : "#f7fafc",
                  color: severityFilter === item.key ? "#087a8c" : "#536987",
                }}
              >
                {item.key === "Critical" && <FiAlertCircle size={14} className="text-[#f5a623]" />}
                <span>{item.label}</span>
                <strong className="rounded-full bg-white px-2 py-0.5 text-[#087a8c]">{loading ? "..." : item.count}</strong>
              </button>
            ))}
          </div>
        </div>

        <div className="border-b border-[#edf2f6] px-4 py-4 text-sm font-semibold text-[#536987]">
          <div>Showing Alerts from :</div>
          <div className="mt-3 text-[#536987]">{showingFrom}</div>
        </div>

        <div className="min-h-0 flex-1 overflow-y-auto px-3 py-3">
          {loading ? (
            <div className="rounded-lg bg-[#f4f8fb] p-5 text-sm font-semibold text-[#7890aa]">Loading alerts...</div>
          ) : visibleCategories.length === 0 ? (
            <div className="rounded-lg bg-[#f4f8fb] p-5 text-sm font-semibold text-[#7890aa]">No alert category matches your search.</div>
          ) : (
            visibleCategories.map((category) => {
              const count = categoryCounts.get(category.key) ?? 0;
              const selected = selectedCategory.key === category.key;
              return (
                <button
                  key={category.key}
                  type="button"
                  onClick={() => setSelectedKey(category.key)}
                  className="mb-2 w-full rounded-lg border p-4 text-left transition"
                  style={{
                    borderColor: selected ? "#e8f0f6" : "transparent",
                    background: selected ? "#f2f7fa" : "#ffffff",
                    boxShadow: selected ? "0 10px 24px rgba(15,23,42,0.06)" : "none",
                  }}
                >
                  <div className="flex items-start gap-2">
                    {category.autoGenerated && <FiAlertCircle className="mt-0.5 shrink-0 text-[#f5a623]" size={15} />}
                    <div className="min-w-0">
                      <div className="text-sm font-bold leading-snug text-[#536987]">
                        <span className={selected ? "text-[#087a8c]" : ""}>{category.title} :</span>{" "}
                        <strong className="text-[#061337]">{category.autoGenerated || count > 0 ? count : "No Alert Set"}</strong>
                      </div>
                      {category.description && <p className="mt-3 text-xs font-medium leading-6 text-[#536987]">{category.description}</p>}
                      {category.autoGenerated && (
                        <span className="mt-3 inline-flex rounded-md bg-[#dbeaf4] px-4 py-2 text-xs font-bold text-[#536987]">Auto Generated</span>
                      )}
                      <div className="mt-4 text-xs font-semibold text-[#b5c7d6]">
                        <span className="font-bold text-[#23b8c8]">Set alert</span>{" "}
                        {category.autoGenerated ? "to receive notifications" : "to Receive Data"}
                      </div>
                    </div>
                  </div>
                </button>
              );
            })
          )}
        </div>
      </aside>

      <main className="min-w-0 flex-1 overflow-hidden p-5">
        <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
          <h1 className="text-xl font-extrabold text-[#061337]">Alerts</h1>
          <div className="flex items-center gap-3">
            <select
              value={period}
              onChange={(event) => setPeriod(event.target.value as PeriodKey)}
              className="h-10 min-w-[190px] rounded-lg border border-[#d5e2ec] bg-white px-4 text-sm font-semibold text-[#536987] outline-none"
            >
              {Object.entries(PERIODS).map(([key, item]) => <option key={key} value={key}>{item.label}</option>)}
            </select>
            <button type="button" onClick={load} className="grid h-10 w-10 place-items-center rounded-lg border border-[#edf2f6] bg-white text-[#536987]" aria-label="Refresh alerts">
              <FiBell size={18} />
            </button>
          </div>
        </div>

        <div className="mb-4 flex flex-wrap items-center justify-between gap-3">
          <h2 className="text-base font-extrabold text-[#061337]">{selectedCategory.title} Alerts</h2>
          <div className="flex items-center gap-3">
            <button type="button" className="grid h-10 w-10 place-items-center rounded-lg bg-white text-[#536987]" aria-label="Search table">
              <FiSearch size={21} />
            </button>
            <button type="button" className="inline-flex h-10 items-center gap-2 rounded-full bg-white px-5 text-sm font-bold text-[#536987]">
              <FiChevronLeft size={16} /> Filters
            </button>
            <button type="button" className="grid h-10 w-10 place-items-center rounded-lg bg-white text-[#536987]" aria-label="Download alerts">
              <FiDownload size={18} />
            </button>
            <button type="button" className="grid h-10 w-10 place-items-center rounded-lg bg-white text-[#536987]" aria-label="Send alerts">
              <FiMail size={18} />
            </button>
          </div>
        </div>

        <div className="h-[calc(100%-92px)] overflow-hidden rounded-lg bg-white shadow-[0_12px_30px_rgba(15,23,42,0.06)]">
          <div className="grid grid-cols-[1.1fr_1fr_1fr_1fr] bg-[#dceaf4] px-5 py-4 text-xs font-extrabold text-[#536987]">
            <div>Vehicle Number</div>
            <div>Driver</div>
            <div>{selectedCategory.key === "ignition" ? "Ignition On Time" : "Alert Time"}</div>
            <div>{selectedCategory.key === "ignition" ? "Ignition Off Time" : "Details"}</div>
          </div>

          <div className="h-[calc(100%-48px)] overflow-auto">
            {loading ? (
              <div className="py-16 text-center text-sm font-semibold text-[#7890aa]">Loading alerts...</div>
            ) : selectedAlerts.length === 0 ? (
              <div className="py-16 text-center text-sm font-semibold text-[#7890aa]">No records for this alert type in the selected period.</div>
            ) : (
              selectedAlerts.map((alert) => {
                const severity = norm(alert.severity || "INFO");
                return (
                  <div key={alert.id ?? `${alert.alertType}-${alertTime(alert)}`} className="grid min-h-[78px] grid-cols-[1.1fr_1fr_1fr_1fr] items-center border-b border-[#eef2f6] px-5 text-sm font-semibold text-[#536987]">
                    <div className="truncate">{vehicleName(alert, deviceMaps)}</div>
                    <div className="truncate">{driverName(alert, deviceMaps)}</div>
                    <div>{dateText(alertTime(alert))}</div>
                    <div className="min-w-0">
                      {selectedCategory.key === "ignition" ? (
                        alert.ackAt ? dateText(alert.ackAt) : "-"
                      ) : (
                        <div className="flex items-center gap-2">
                          <span className="h-2 w-2 rounded-full" style={{ background: SEVERITY_STYLE[severity] ?? "#1A7A75" }} />
                          <span className="truncate">{alert.message ?? alert.relatedGeofenceName ?? alert.alertType ?? "-"}</span>
                        </div>
                      )}
                    </div>
                  </div>
                );
              })
            )}
          </div>
        </div>

        <div className="mt-4 flex items-center justify-end gap-4 text-sm font-semibold text-[#536987]">
          <span>Showing {selectedAlerts.length === 0 ? 0 : 1} - {selectedAlerts.length} of {selectedAlerts.length}</span>
          <button type="button" className="grid h-8 w-8 place-items-center text-[#b5c7d6]" aria-label="Previous page">
            <FiChevronLeft />
          </button>
          <span className="grid h-10 w-10 place-items-center rounded-lg bg-white text-[#061337]">1</span>
          <span>/ 1</span>
          <button type="button" className="grid h-8 w-8 place-items-center text-[#b5c7d6]" aria-label="Next page">
            <FiChevronRight />
          </button>
        </div>
      </main>
    </div>
  );
}
